import type {
  BuffersPillar,
  ComfortPillar,
  EnergyPillar,
  FoodPillar,
  HeatingFuelData,
  WaterPillar,
} from "./types";

export interface StarterProfile {
  id: string;
  name: string;
  description: string;
  energy: EnergyPillar;
  water: WaterPillar;
  food: FoodPillar;
  comfort: ComfortPillar;
  buffers: BuffersPillar;
  heating_fuel: Partial<HeatingFuelData>;
}

export const STARTER_PROFILES: StarterProfile[] = [
  {
    id: "bare_land",
    name: "Bare Land",
    description: "Raw acreage, no structures yet",
    energy: {
      solar_kw: 0,
      battery_kwh: 0,
      generator: false,
      winter_sun_hours: 4,
      daily_kwh_use: 3,
    },
    water: {
      primary_source: "rain",
      storage_gallons: 50,
      gravity_option: false,
      filtration_level: "basic",
    },
    food: {
      garden_sqft: 0,
      chickens_count: 0,
      goats_count: 0,
      root_cellar: false,
      stored_food_months: 1,
    },
    comfort: {
      heat_type: "wood",
      cooking_type: "wood",
      backup_heat: false,
      backup_cooking: false,
    },
    buffers: {
      fuel_reserve_days: 7,
      feed_reserve_days: 0,
      spare_parts_kit: "none",
      resupply_trips_per_month: 4,
    },
    heating_fuel: {
      firewood_cords: 0,
      firewood_role: "occasional",
      propane_uses_heating: false,
      propane_uses_cooking: false,
      propane_uses_water_heater: false,
      propane_uses_generator: false,
      heated_sqft: 600,
      insulation_level: "poor",
      heating_priority: "survival_heat",
      winterTempBand: "cool",
      snowDisruption: "occasional",
      propane_fill_percent: 0,
      propane_tank_preset: 100,
    },
  },
  {
    id: "basic_rural_home",
    name: "Basic Rural Home",
    description: "A modest house with basic systems in place",
    energy: {
      solar_kw: 2,
      battery_kwh: 5,
      generator: false,
      winter_sun_hours: 4,
      daily_kwh_use: 8,
    },
    water: {
      primary_source: "well",
      storage_gallons: 200,
      gravity_option: false,
      filtration_level: "good",
    },
    food: {
      garden_sqft: 400,
      chickens_count: 4,
      goats_count: 0,
      root_cellar: false,
      stored_food_months: 3,
    },
    comfort: {
      heat_type: "propane",
      cooking_type: "gas",
      backup_heat: true,
      backup_cooking: false,
    },
    buffers: {
      fuel_reserve_days: 30,
      feed_reserve_days: 14,
      spare_parts_kit: "basic",
      resupply_trips_per_month: 2,
    },
    heating_fuel: {
      firewood_cords: 2,
      firewood_role: "secondary",
      propane_uses_heating: true,
      propane_uses_cooking: true,
      propane_uses_water_heater: true,
      propane_uses_generator: false,
      heated_sqft: 1200,
      insulation_level: "average",
      heating_priority: "whole_house",
      winterTempBand: "cool",
      snowDisruption: "occasional",
      propane_tank_preset: 250,
      propane_fill_percent: 60,
    },
  },
  {
    id: "mountain_homestead",
    name: "Mountain Homestead",
    description: "A well-sited rural property with seasonal challenges",
    energy: {
      solar_kw: 4,
      battery_kwh: 10,
      generator: true,
      winter_sun_hours: 4,
      daily_kwh_use: 10,
    },
    water: {
      primary_source: "spring",
      storage_gallons: 500,
      gravity_option: true,
      filtration_level: "excellent",
    },
    food: {
      garden_sqft: 800,
      chickens_count: 8,
      goats_count: 2,
      root_cellar: true,
      stored_food_months: 6,
    },
    comfort: {
      heat_type: "wood",
      cooking_type: "wood",
      backup_heat: true,
      backup_cooking: true,
    },
    buffers: {
      fuel_reserve_days: 60,
      feed_reserve_days: 30,
      spare_parts_kit: "solid",
      resupply_trips_per_month: 1,
    },
    heating_fuel: {
      firewood_cords: 4,
      firewood_role: "primary",
      propane_uses_heating: false,
      propane_uses_cooking: false,
      propane_uses_water_heater: false,
      propane_uses_generator: true,
      heated_sqft: 1400,
      insulation_level: "good",
      heating_priority: "living_area",
      winterTempBand: "cold",
      snowDisruption: "regular",
      propane_tank_preset: 250,
      propane_fill_percent: 70,
    },
  },
  {
    id: "well_prepared_homestead",
    name: "Well-Prepared Homestead",
    description: "A thoughtfully equipped property with redundancy",
    energy: {
      solar_kw: 6,
      battery_kwh: 20,
      generator: true,
      winter_sun_hours: 5,
      daily_kwh_use: 12,
    },
    water: {
      primary_source: "well",
      storage_gallons: 1000,
      gravity_option: true,
      filtration_level: "excellent",
    },
    food: {
      garden_sqft: 1200,
      chickens_count: 12,
      goats_count: 4,
      root_cellar: true,
      stored_food_months: 9,
    },
    comfort: {
      heat_type: "wood",
      cooking_type: "mixed",
      backup_heat: true,
      backup_cooking: true,
    },
    buffers: {
      fuel_reserve_days: 90,
      feed_reserve_days: 60,
      spare_parts_kit: "solid",
      resupply_trips_per_month: 1,
    },
    heating_fuel: {
      firewood_cords: 6,
      firewood_role: "primary",
      propane_uses_heating: true,
      propane_uses_cooking: true,
      propane_uses_water_heater: true,
      propane_uses_generator: false,
      heated_sqft: 1600,
      insulation_level: "good",
      heating_priority: "whole_house",
      winterTempBand: "cold",
      snowDisruption: "occasional",
      propane_tank_preset: 500,
      propane_fill_percent: 75,
    },
  },
  {
    id: "off_grid_setup",
    name: "Off-Grid Setup",
    description: "A fully independent, off-grid homestead",
    energy: {
      solar_kw: 8,
      battery_kwh: 30,
      generator: true,
      winter_sun_hours: 5,
      daily_kwh_use: 15,
    },
    water: {
      primary_source: "spring",
      storage_gallons: 2000,
      gravity_option: true,
      filtration_level: "excellent",
    },
    food: {
      garden_sqft: 2000,
      chickens_count: 20,
      goats_count: 6,
      root_cellar: true,
      stored_food_months: 12,
    },
    comfort: {
      heat_type: "wood",
      cooking_type: "wood",
      backup_heat: true,
      backup_cooking: true,
    },
    buffers: {
      fuel_reserve_days: 180,
      feed_reserve_days: 90,
      spare_parts_kit: "solid",
      resupply_trips_per_month: 0,
    },
    heating_fuel: {
      firewood_cords: 8,
      firewood_role: "primary",
      propane_uses_heating: false,
      propane_uses_cooking: true,
      propane_uses_water_heater: true,
      propane_uses_generator: false,
      heated_sqft: 1000,
      insulation_level: "excellent",
      heating_priority: "living_area",
      winterTempBand: "cold",
      snowDisruption: "regular",
      propane_tank_preset: 500,
      propane_fill_percent: 80,
    },
  },
];
